# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Run on monitor connect/disconnect
exec-once = hyprland-monitor-attached ~/dotfiles/hypr/bin/hypr-monitor-toggle ~/dotfiles/hypr/bin/hypr-monitor-toggle
# Also run on Hyprland reload so it doesn't revert
exec = ~/dotfiles/hypr/bin/hypr-monitor-toggle
